[Service]
Environment=APPLE_SERVER_API_ISSUER_ID=fb2f1b49-8130-4cb9-a1bc-584e6adff0a4
Environment=APPLE_SERVER_API_KEY_ID=F75KHF9938
Environment=APPLE_SERVER_API_PRIVATE_KEY_FILE=/opt/gw-alloc/secrets/SubscriptionKey_F75KHF9938.p8
Environment=APPLE_SERVER_API_RECONCILE_INTERVAL_SEC=900
Environment=APPLE_SERVER_API_RECONCILE_LOOKBACK_SEC=86400
